version: '3.8'

services:
  spring-app:
    container_name: gc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9010:9010"
    env_file:
      - .env
    volumes:
      - ./logs:/logs
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitor-net
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:

networks:
  monitor-net: